"""tsvector

Revision ID: 679e6bb7fe8f
Revises: d7ebfb880ca6
Create Date: 2026-05-07 10:49:57.006913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679e6bb7fe8f'
down_revision: Union[str, Sequence[str], None] = 'd7ebfb880ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE FUNCTION papers_search_trigger() RETURNS trigger AS $$
    BEGIN
        NEW.search_vector :=
            to_tsvector('english', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.abstract, ''));
        RETURN NEW;
    END
    $$ LANGUAGE plpgsql;
    """)

    # Create trigger
    op.execute("""
    CREATE TRIGGER update_papers_search_vector
    BEFORE INSERT OR UPDATE ON papers
    FOR EACH ROW EXECUTE FUNCTION papers_search_trigger();
    """)

    # Backfill existing rows
    op.execute("""
    UPDATE papers
    SET search_vector = to_tsvector('english', title || ' ' || abstract);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_papers_search_vector ON papers;")
    op.execute("DROP FUNCTION IF EXISTS papers_search_trigger();")
    # ### end Alembic commands ###
