"""message

Revision ID: 67ed18da09cc
Revises: c7119e50366d
Create Date: 2026-05-05 17:07:21.330185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ed18da09cc'
down_revision: Union[str, Sequence[str], None] = 'c7119e50366d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_author_affiliation', 'author', ['auth_name', 'affiliation'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_author_affiliation', 'author', type_='unique')
    # ### end Alembic commands ###
