"""message

Revision ID: c7119e50366d
Revises: 0705a679015e
Create Date: 2026-05-04 00:14:02.137899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7119e50366d'
down_revision: Union[str, Sequence[str], None] = '0705a679015e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auth_name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('papers',
    sa.Column('paper_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pdf_link', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.CheckConstraint('publish_date <= CURRENT_DATE', name='check_publish_date'),
    sa.PrimaryKeyConstraint('paper_id'),
    sa.UniqueConstraint('doi')
    )
    op.create_index('idx_search_vector', 'papers', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'author', name='user_role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cites',
    sa.Column('citing_paper', sa.Integer(), nullable=False),
    sa.Column('cited_paper', sa.Integer(), nullable=False),
    sa.CheckConstraint('citing_paper <> cited_paper', name='check_no_self_cite'),
    sa.ForeignKeyConstraint(['cited_paper'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_paper'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citing_paper', 'cited_paper')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('reads',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'paper_id')
    )
    op.create_table('writes',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['author.auth_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_id', 'paper_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writes')
    op.drop_table('reads')
    op.drop_table('comment')
    op.drop_table('cites')
    op.drop_table('users')
    op.drop_index('idx_search_vector', table_name='papers', postgresql_using='gin')
    op.drop_table('papers')
    op.drop_table('author')
    # ### end Alembic commands ###
